name: Build OtzarotApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore
      run: dotnet restore OtzarotApp/OtzarotApp.csproj

    - name: Build
      run: msbuild OtzarotApp/OtzarotApp.csproj /p:Platform=x64 /p:Configuration=Release /t:Build /nologo
